backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github


publish_mode: editorial_workflow

media_folder: "public/images/photo"
public_folder: "/images/photo"

collections:
  - name: "photo"
    label: "photos"
    folder: "src/photo"
    create: true
    fields:
    - { name: 'title', label: 'Titre', widget: 'string'}
    - { name: 'image', label: 'Image', widget: 'image'}
    - { name: 'category', label: 'Catégorie', widget: 'string'}
