backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github


publish_mode: editorial_workflow

media_folder: "src/images/Photos"
public_folder: "/images/Photos"

collections:
  - name: "photo"
    label: "Photos"
    folder: "src/Photos"
    create: true
    fields:
    - { name: 'title', label: 'Titre', widget: 'string'}
    - { name: 'image', label: 'Image', widget: 'image', media_library: { config: { public_folder: "/images/Photos" }}}
    - { name: 'category', label: 'Catégorie', widget: 'string'}
