backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github
    config:
      client_id: your-github-client-id
      client_secret: your-github-client-secret

  # This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://raw.githubusercontent.com/Tom-Mai/ECF-Charles-Cantin-11ty/main/src/assets/images/logo_admin.png
# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads" # Public files will be stored in the repo under images/uploads

collections:
  - name: "photo"
    label: "Photos"
    folder: "src/Photos"
    create: true
    fields:
    - { name: 'title', label: 'Titre', widget: 'string'}
    - { name: 'image', label: 'Image', widget: 'image', media_library: { config: { public_folder: \public\images\uploads" }}}
    - { name: 'category', label: 'Catégorie', widget: 'string'}

images/blog

