backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github

local_backend: true

logo_url: https://github.com/Tom-Mai/ECF-Charles-Cantin-11ty/blob/cde433a3a45ff14504c00914389ddcd39c3bef9c/src/assets/images/logo_admin.png?raw=true
media_folder: "public/images/photo"
public_folder: "/images/photo"

collections:
  - name: "photo"
    label: "photos"
    folder: "src/photo"
    create: true
    slug: '{{pageName}}'
    fields:
    - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
    - { label: 'Featured Image', name: 'image', widget: 'image' }
    - { label: 'Catégorie', name: 'category', widget: 'string' }
