backend:
  name: git-gateway
  branch: main

  # This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://github.com/Tom-Mai/ECF-Charles-Cantin-11ty/blob/a31451d7f3175ba28ed1c942bfa78c8626bfd041/src/assets/images/logo/logo-fb.png
# This line should *not* be indented
media_folder: "public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{pageName}}"
    fields:
      - {
          label: "Page-Name-with-dashes-only",
          name: "pageName",
          widget: "string",
        }
      - { label: "Blog Title", name: "blogTitle", widget: "string" }
      - { label: "Title Tag", name: "titleTag", widget: "string" }
      - { label: "Description", name: "blogDescription", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
