backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github


publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "photo"
    label: "photos"
    folder: "src/photo"
    create: true
    slug: '{{pageName}}'
    fields:
    - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
    - { label: 'Featured Image', name: 'image', widget: 'image' }
    - { label: 'Catégorie', name: 'category', widget: 'string' }
