backend:
  name: git-gateway
  branch: main
  repo: Tom-Mai/ECF-Charles-Cantin-11ty
  auth_provider:
    name: github

local_backend: true

logo_url: https://github.com/Tom-Mai/ECF-Charles-Cantin-11ty/blob/cde433a3a45ff14504c00914389ddcd39c3bef9c/src/assets/images/logo_admin.png?raw=true
media_folder: 'public/image/photo'
public_folder: '/image/photo'

collections:
  - name: 'photo'
    label: 'photos'
    folder: 'src/photo'
    create: true
    slug: '{{pageName}}'
    fields:
    - { label: 'Name of picture', name: 'PictureName', widget: 'string' }
    - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
    - { label: 'Featured Image', name: 'image', widget: 'image' }
    - { label: 'Catégorie', name: 'category', widget: 'string' }
    - { label: 'Tags', name: 'tags', widget: 'list', default: ['post'] }


  - name: 'price'
    label: 'Price'
    folder: 'src/photo'
    create: true
    fields:
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['price'] }
      - { label: 'Titre du tarif', name: 'tarif', widget: 'string' }
      - { label: 'Catégorie', name: 'category', widget: 'string' }
      - { label: 'Image Caption', name: 'imageAlt', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'priceDescription', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'string' }
