backend:
  name: git-gateway
  branch: main
  # This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "src/assets/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "assets/images/uploads" # Public files will be stored in the repo under
